kind: pipeline
type: docker
name: default

steps:
- name: terraform-init
  image: hashicorp/terraform:1.3.6
  commands:
    - "terraform init"

- name: terraform-plan
  image: hashicorp/terraform:1.3.6
  commands:
    - "terraform plan"
