kind: pipeline
type: docker
name: default

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./plugin-cache

- name: terraform-init
  image: hashicorp/terraform:1.3.6
  commands:
    - "terraform init"

- name: terraform-plan
  image: hashicorp/terraform:1.3.6
  commands:
    - "terraform plan"

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./plugin-cache

volumes:
  - name: cache
    host:
      path: /tmp/terraform-plugin-cache
